name: Quality check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RafikFarhad/clang-format-github-action@v4
        with:
          sources: "esp32-different-i2c-buses-example/*.ino"
          style: file
